/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DashboardImport } from './routes/_dashboard'
import { Route as AuthImport } from './routes/_auth'
import { Route as IndexImport } from './routes/index'
import { Route as DashboardProfileImport } from './routes/_dashboard.profile'
import { Route as DashboardDashboardImport } from './routes/_dashboard.dashboard'
import { Route as AuthRegisterImport } from './routes/_auth.register'
import { Route as AuthLoginImport } from './routes/_auth.login'
import { Route as DashboardProductsIndexImport } from './routes/_dashboard.products.index'
import { Route as DashboardProfileRecoverImport } from './routes/_dashboard.profile.recover'
import { Route as DashboardProfileEditImport } from './routes/_dashboard.profile.edit'
import { Route as DashboardProductsNewImport } from './routes/_dashboard.products.new'
import { Route as DashboardProductsIdImport } from './routes/_dashboard.products.$id'

// Create/Update Routes

const DashboardRoute = DashboardImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardProfileRoute = DashboardProfileImport.update({
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardDashboardRoute = DashboardDashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => DashboardRoute,
} as any)

const AuthRegisterRoute = AuthRegisterImport.update({
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)

const DashboardProductsIndexRoute = DashboardProductsIndexImport.update({
  path: '/products/',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardProfileRecoverRoute = DashboardProfileRecoverImport.update({
  path: '/recover',
  getParentRoute: () => DashboardProfileRoute,
} as any)

const DashboardProfileEditRoute = DashboardProfileEditImport.update({
  path: '/edit',
  getParentRoute: () => DashboardProfileRoute,
} as any)

const DashboardProductsNewRoute = DashboardProductsNewImport.update({
  path: '/products/new',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardProductsIdRoute = DashboardProductsIdImport.update({
  path: '/products/$id',
  getParentRoute: () => DashboardRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_dashboard': {
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/_auth/login': {
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof AuthImport
    }
    '/_auth/register': {
      preLoaderRoute: typeof AuthRegisterImport
      parentRoute: typeof AuthImport
    }
    '/_dashboard/dashboard': {
      preLoaderRoute: typeof DashboardDashboardImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/profile': {
      preLoaderRoute: typeof DashboardProfileImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/products/$id': {
      preLoaderRoute: typeof DashboardProductsIdImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/products/new': {
      preLoaderRoute: typeof DashboardProductsNewImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/profile/edit': {
      preLoaderRoute: typeof DashboardProfileEditImport
      parentRoute: typeof DashboardProfileImport
    }
    '/_dashboard/profile/recover': {
      preLoaderRoute: typeof DashboardProfileRecoverImport
      parentRoute: typeof DashboardProfileImport
    }
    '/_dashboard/products/': {
      preLoaderRoute: typeof DashboardProductsIndexImport
      parentRoute: typeof DashboardImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AuthRoute.addChildren([AuthLoginRoute, AuthRegisterRoute]),
  DashboardRoute.addChildren([
    DashboardDashboardRoute,
    DashboardProfileRoute.addChildren([
      DashboardProfileEditRoute,
      DashboardProfileRecoverRoute,
    ]),
    DashboardProductsIdRoute,
    DashboardProductsNewRoute,
    DashboardProductsIndexRoute,
  ]),
])

/* prettier-ignore-end */
